### ISSUE TITLE
warnings about listeners

### ISSUE THREAD

**Issue by btbonval** [AndrewMagliozzi/mit-ocw-scraper#1]
I ran npm to get the modules up to date, then ran mit-scraper. I got a warning about a possible EventEmitter memory leak which repeated 4 times, ~~and then the program ended. No files were written to disk~~.

```
$ nodejs mit-scraper.js
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.EventEmitter.addListener (events.js:160:15)
    at Socket.Readable.on (_stream_readable.js:689:33)
    at Socket.EventEmitter.once (events.js:185:8)
    at Request.onResponse (/vagrant/ocw/node_modules/request/request.js:625:25)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:525:27)
```

**Comment by btbonval** [comment]
ack wrong branch. I was using `master` branch.

**Comment by btbonval** [comment]
`mit-notes` branch throws that same warning 5 times.

still waiting on file output.

**Comment by btbonval** [comment]
files were output. I'll update the main ticket block to cross that part out.
