### ISSUE TITLE
slash in names needs to be replaced or escaped

### ISSUE THREAD

**Issue by btbonval** [AndrewMagliozzi/mit-ocw-scraper#2]
A course with a slash in it was treated as a directory, crashing the execution.

Slashes should be escaped (`\/`) or replaced (say with a - or %2f).

```
Error: ENOENT, no such file or directory 'Comparative Media Studies/Writing.json
'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at Request._callback (/vagrant/ocw/mit-scraper.js:92:14)   
    at Request.self.callback (/vagrant/ocw/node_modules/request/request.js:129:2
2)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/vagrant/ocw/node_modules/request/request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/vagrant/ocw/node_modules/request/request.js:824:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
```

**Comment by btbonval** [comment]
Tried replacing `/` with `\/`, which gave the error `Error: ENOENT, no such file or directory 'Comparative Media Studies\/Writing.json'`. Not helpful.

Tried replacing '/' with `-` and it made the file no problem. There should be a way to write a file with `/` from Node. I don't like the data loss from replacing the character entirely.

**Comment by btbonval** [comment]
I just learned something today: unix does not like slashes in file names, at least not on ext4. That seems really strange because `/` is just a user interface convention, it should be just as escapable as anything else. It's not like the inode should care.

Alright, let's replace it with something that is understood to be related back. `%2f` isn't pretty but it makes sense from a URL standpoint. Guess I'll do that.
